### ISSUE TITLE
Try to seek for race conditions occurring in Actions only

### ISSUE THREAD

**Issue by bertllll** [MASQ-Project/Node-issues#389]
I've experienced them more than little times in:  Node/masq/communication/communication_manager 
at more places in there.

**Comment by dnwiebe** [comment]
We can move this out of Backlog when we get some specific details about particular tests that fail sometimes but not always in Actions. When you experience that, post a description in a comment here and attach the downloaded console log from Actions.

**Comment by bertllll** [comment]
I got this when this area was not affected by the particular card (GH-381). Happened after a break from any strangely failing tests, now,  when a new Rust version came.

thread 'main' panicked at 'ClientListenerThread could not be restarted: Timeout', D:\a\Node\Node\masq\src\communications\connection_manager.rs:455:23
stack backtrace:
   0:     0x7ff74c24187e - std::backtrace_rs::backtrace::dbghelp::trace
test communications::connection_manager::tests::handles_outgoing_fire_and_forget_messages_to_dead_server ... FAILED
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff74c24187e - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff74c24187e - std::sys_common::backtrace::_print_fmt
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\sys_common\backtrace.rs:67

**Comment by bertllll** [comment]
This problem occurred at the same day as the previous but I didn't have time to report it. It showed itself once and in the next run Actions did not complain though I did no changes in the code. 

![log multinode test](https://user-images.githubusercontent.com/65427484/107931689-eabfd380-6f7c-11eb-9e48-094dbc3c561f.png)

**Comment by bertllll** [comment]
Sorry. This is not going to help highly likely. It could have been either of http_end_to_end_routing_test() or 
http_end_to_end_routing_test_with_consume_and_originate_only_nodes()

![race_con_actions 16 2](https://user-images.githubusercontent.com/65427484/108083526-73b93680-7073-11eb-9815-da8a10448fc4.png)

I'll keep in mind to get a full bunch of the genuine log files, when another failure happens again.

**Comment by dnwiebe** [comment]
One of the multinode tests failed.
[logs_473.zip](https://github.com/MASQ-Project/Node/files/6010133/logs_473.zip)

**Comment by bertllll** [comment]
Windows ...one of node unit tests. No relation to the card being coped. 

[logs_509.zip](https://github.com/MASQ-Project/Node/files/6118124/logs_509.zip)

**Comment by bertllll** [comment]
configurator_standard ... setting gas price

[logs_519.zip](https://github.com/MASQ-Project/Node/files/6136389/logs_519.zip)

**Comment by bertllll** [comment]
windows: tls_through_node_test (integration); I know this test because that's the one which permanently fails on my Win machine. 

[logs_530.zip](https://github.com/MASQ-Project/Node/files/6157697/logs_530.zip)

**Comment by bertllll** [comment]
windows: `tls_through_node_test` (integration); I know this test because that's the one which permanently fails on my Win machine.

[logs_530.zip](https://github.com/MASQ-Project/Node/files/6157723/logs_530.zip)

**Comment by bertllll** [comment]
MacOS: Node: unit_tests:
initialize_with_clandestine_port_produces_expected_clandestine_discriminator_factories_vector

[logs_599.zip](https://github.com/MASQ-Project/Node/files/6264178/logs_599.zip)

**Comment by bertllll** [comment]
an attempt if an archive with logs persists

[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6290202/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
This is unfortunate. By all evidences, GitHub stopped to support zipped packages and these ours which are attached to the comments here are inaccessible by now. I'd be happy if I was wrong.

**Comment by bertllll** [comment]
**handle_startup_and_shutdown_integration**

This test was renovated for this card, GH-386, however, usually it passes, this time it didn't. Maybe RC.

[3_Build node on windows-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6316666/3_Build.node.on.windows-latest.txt)

**Comment by bertllll** [comment]
**handle_redirect_order_disappoints_waiting_conversations_with_resend_or_graceful**

Maybe newly created RC after I did a lot of modifications (GH-386) in the UI where some could affect the connection_manager in his work, well, maybe not. 

[3_Build node on windows-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6316709/3_Build.node.on.windows-latest.txt)

**Comment by bertllll** [comment]
**communications::connection_manager::tests::handles_listener_fallback_from_node**

Another test that I don't remember failing. Again GH-386.

[3_Build node on windows-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6317062/3_Build.node.on.windows-latest.txt)

**Comment by bertllll** [comment]
[logs_29.zip](https://github.com/MASQ-Project/Node-issues/files/6317065/logs_29.zip)

**Comment by bertllll** [comment]
**provided_and_consumed_services_are_recorded_in_databases**

Multinode-integration-test...I dimly remember seeing this before. Again GH-386.

[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6317208/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
**connection_manager::tests::handles_fire_and_forget_outgoing_message**

This has been seen multiple times. 

[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6377141/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
**test_utils::mock_websockets_server::tests::conversational_and_broadcast_messages_can_work_together_testing_corner_cases**

mac_os

[1_Build node on macOS-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6615707/1_Build.node.on.macOS-latest.txt)

**Comment by bertllll** [comment]
I'm adding this after a while passed from when it happened; I found it my Downloads folder. 

**blockchain::blockchain_interface::tests::blockchain_interface_non_clandestine_retrieves_transactions**
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6693630/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
similarly, I found this: 

**websocket_supervisor::tests::send_msg_fails_to_look_up_client_to_send_to**
[3_Build node on windows-latest.txt](https://github.com/MASQ-Project/Node-issues/files/6693655/3_Build.node.on.windows-latest.txt)

**Comment by bertllll** [comment]
Seems like we've got a new one. 
**blockchain::blockchain_interface::tests::blockchain_interface_non_clandestine_retrieve_transactions_returns_an_error_if_a_response_with_data_that_is_too_long_is_returned**
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7092253/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
Too many of blockchain_interface lately, feeling suspicious.
**blockchain::blockchain_interface::tests::blockchain_interface_non_clandestine_retrieve_transactions_ignores_transaction_logs_that_have_no_block_number**
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7092279/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
Failure in Docker:
**multiple_stream_zero_hop_test**
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7092318/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
**neighborhood::gossip_acceptor::tests::standard_gossip_containing_unfamiliar_node_addrs_leads_to_them_being_ignored**
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7092374/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
Multinode ... Docker
**provided_and_consumed_services_are_recorded_in_databases**
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7092389/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
multinode
**downed_nodes_not_offered_in_passes_or_introductions**
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7162082/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
**blockchain::blockchain_interface::tests::blockchain_interface_non_clandestine_can_retrieve_eth_balance_of_a_wallet**
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7162100/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
Don't know why yet, but now a time of a lot of failures in multinode tests has come. 

Another: 
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7167861/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
**pass_args_or_print_messages_work_under_fine_lock_for_eof**

I guess this is a rare one. I suggest just to increase the multiplier in the assertion like from 3 to 4 or something. I know there is a couple of tests like this and this was the latest I added, maybe the chosen multiplier doesn't fit as well as for the other tests, I think its value could be a bit test specific. 

[1_Build node on macOS-latest.txt](https://github.com/MASQ-Project/Node-issues/files/7449934/1_Build.node.on.macOS-latest.txt)

**Comment by bertllll** [comment]
**tls_through_node_integration**

This one is really rare in Actions I think, on the other hand we come to see it quite often on dev machines. Speaking mainly for myself (maybe occurred almost all the time) but I also saw it at Utkarsh.
 
[3_Build node on windows-latest.txt](https://github.com/MASQ-Project/Node-issues/files/8031286/3_Build.node.on.windows-latest.txt)

**Comment by dnwiebe** [comment]
The multinode test tls_end_to_end_routing_test hung for most of five hours. We don't know why, but here's the log.

[logs_830.zip](https://github.com/MASQ-Project/Node-issues/files/8060625/logs_830.zip)
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/8060638/2_Build.node.on.ubuntu-latest.txt)

**Comment by utkarshg6** [comment]
**graph_connects_but_does_not_over_connect**
[1_build.txt](https://github.com/MASQ-Project/Node-issues/files/8178375/1_build.txt)
[2_Build node on ubuntu-latest.txt](https://github.com/MASQ-Project/Node-issues/files/8178377/2_Build.node.on.ubuntu-latest.txt)

**Comment by bertllll** [comment]
**http_through_node_integration**

[1_Build node on macOS-latest.txt](https://github.com/MASQ-Project/Node-issues/files/8500603/1_Build.node.on.macOS-latest.txt)
